# -*- coding: utf-8 -*-
"""Generate Annex 2.1 (price tiers) and Annex 2.2 (covered jurisdictions) of the
Septeo reseller agreement from curation/price_bands.json.

The annex used to be hand-edited, drifted from the data, and the drift was
invisible: on 14.09.2026 the tier counts matched by coincidence while the
underlying sets differed. Nothing in section 2.1 or 2.2 may be typed by hand
again -- edit the JSON, re-run this, and let --check fail the build if someone
does it anyway.

    python scripts/build_annex2.py --check     # exit 1 if the document drifted
    python scripts/build_annex2.py --write     # regenerate the two sections
    python scripts/build_annex2.py             # print the fragments

Annex 2a as a separate price list was removed on 15.09.2026: the amounts
now sit in Annex 2.1 of the Agreement itself.

Procurement costs are the CONTRACTED per-case fees from the supply Order Form,
not the list prices on the coverage page. They live here because they are a
commercial term of our own, not a property of the coverage data.
"""
from __future__ import print_function

import argparse
import collections
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
BANDS = os.path.join(REPO, "curation", "price_bands.json")
DOC = os.path.join(REPO, "docs", "SEPTEO_RESELLER_AGREEMENT_2026-09-14.html")

# tier -> (contracted procurement cost, list price shown for information)
TIER_COST = {
    "A": ("10,80", "15,00"),
    "B": ("26,70", "35,00"),
    "C": ("54,50", "70,00"),
    "D": ("70,50", "90,00"),
}
BAND_TO_TIER = {"Low": "A", "Medium": "B", "High": "C", "Premium": "D"}

TIER_BLURB = {
    "A": "the general case &mdash; open national registers",
    "B": "registers charging a per-document fee",
    "C": "fee-heavy or court-administered registers",
    "D": "offshore registers with a special tariff",
}

# Jurisdictions priced individually rather than by tier.
#
# These are NOT all "direct routes". Until 15.09.2026 the annex said GB, DE and
# US were served by our own direct routes at 1,70 / 6,30 / 17,35 EUR -- but those
# three figures are the SUPPLIER's Home Band fees from our Order Form, not our
# own sourcing. Our own direct routes are DE (handelsregister), FR (INPI) and
# DK (CVR). The two facts were conflated; keep them apart here.
INDIVIDUAL = [("GB", "United Kingdom", "1,70"),
              ("DE", "Germany", "6,30"),
              ("US", "United States", "17,35")]
OWN_ROUTES = ["DE", "FR", "DK"]
MANUAL_SURCHARGE = "3,50"

STP15 = ["FR", "IT", "GB", "US", "ES", "DK", "NL", "LU", "CH", "IL",
         "JP", "BE", "KW", "SG", "HK"]

REGION_ORDER = ["Europe", "Americas", "Asia", "Middle East", "Africa", "Oceania"]

BEGIN = "<!-- BEGIN generated by scripts/build_annex2.py -- do not edit by hand -->"
END = "<!-- END generated -->"


def load():
    with io.open(BANDS, encoding="utf-8") as fh:
        return json.load(fh)


def tier_of(entry):
    return BAND_TO_TIER.get(entry["band"])


def counts(js):
    c = collections.Counter()
    for entry in js.values():
        t = tier_of(entry)
        if t:
            c[t] += 1
    return c


def tiers_fragment(js):
    """Annex 2.1: the tier structure, the procurement cost per tier, and the
    number of jurisdictions in each.

    The amounts lived in a separate Annex 2a price list for part of 15.09.2026
    and were folded back in on instruction. Note what they reveal: the tiers map
    1:1 onto the supplier's public bands (19/49/89/119 US$), so the cost column
    shows a consistent 35-40% discount and identifies the supply side to anyone
    who compares. That is a disclosure decision, taken deliberately."""
    c = counts(js)
    untiered = sorted(cc for cc, e in js.items() if tier_of(e) is None)
    rows = []
    for tier in ("A", "B", "C", "D"):
        cost, lst = TIER_COST[tier]
        rows.append(
            u'          <tr><td class="klass">%s</td>'
            u'<td class="price">%s &euro;</td>'
            u'<td class="price soft">%s &euro;</td>'
            u'<td class="price">%d</td></tr>' % (tier, cost, lst, c[tier]))

    note = u""
    if untiered:
        names = u", ".join(js[cc]["en"] for cc in untiered)
        note = (u'\n    <p><strong>%s is not on a tier.</strong> It has no single '
                u'national register: company records are filed with each state, and '
                u'availability is determined per state. Its cost is agreed separately '
                u'and remains provisional under clause&nbsp;8.6; Annex&nbsp;2.2 marks '
                u'it accordingly.</p>' % names)

    return u"""%(begin)s
    <div class="tablewrap">
      <table class="price-table">
        <thead><tr>
          <th>Tier</th>
          <th class="price">Procurement cost</th>
          <th class="price">List price (for information)</th>
          <th class="price">Jurisdictions</th>
        </tr></thead>
        <tbody>
%(rows)s
        </tbody>
      </table>
    </div>
    <p>A case that has to be worked manually carries a surcharge, notified in advance under Annex&nbsp;2.3. All amounts are net of VAT. The list price column is shown for orientation only and is not the basis of any settlement.</p>%(note)s
    %(end)s""" % {
        "begin": BEGIN, "rows": u"\n".join(rows), "note": note, "end": END,
    }


def jurisdictions_fragment(js, data=None):
    by_region = collections.defaultdict(list)
    for cc, e in js.items():
        by_region[e.get("region", "Other")].append((cc, e["en"], tier_of(e)))

    order = [r for r in REGION_ORDER if r in by_region]
    order += sorted(r for r in by_region if r not in REGION_ORDER)

    out = []
    for region in order:
        rows = sorted(by_region[region], key=lambda r: r[1])
        out.append(u'    <div class="reg-title">%s <span>%d</span></div>'
                   % (region, len(rows)))
        out.append(u'    <div class="chips">')
        for cc, name, tier in rows:
            cls = "chip stp" if cc in STP15 else "chip"
            label = tier if tier else "&mdash;"
            out.append(u'      <span class="%s">%s<b>%s</b></span>' % (cls, name, label))
        out.append(u'    </div>')

    # Sub-registers. A parent with no single national register is NOT covered as
    # a country: only these resolve. Listing "United States" flat, as the annex
    # did until 15.09.2026, states coverage the service does not have.
    subs = (data or {}).get("subJurisdictions") or {}
    if subs:
        out.append(u'    <div class="reg-title">Sub-registers &mdash; where the parent '
                   u'jurisdiction has no single national register <span>%d</span></div>'
                   % sum(len(v) for v in subs.values()))
        for parent in sorted(subs):
            pname = js.get(parent, {}).get("en", parent)
            out.append(u'    <p class="subnote"><strong>%s</strong> resolves only in the '
                       u'following %d, and a Case can be placed only in one of them:</p>'
                       % (pname, len(subs[parent])))
            out.append(u'    <div class="chips">')
            for e in subs[parent]:
                tier = BAND_TO_TIER.get(e.get("band")) or u"&mdash;"
                out.append(u'      <span class="chip sub">%s<b>%s</b></span>'
                           % (e["en"], tier))
            out.append(u'    </div>')

    nsub = sum(len(v) for v in subs.values())
    intro = (u'    <p>%d jurisdictions are covered, together with %d named sub-registers '
             u'listed at the end. The '
             u'<span class="chip stp inline">highlighted<b>&nbsp;</b></span> entries are '
             u"STP's fifteen priority jurisdictions; the letter is the price tier per "
             u'section&nbsp;2.1, and &mdash; marks a jurisdiction that is not on a tier. '
             u'Where a jurisdiction has no single national register, it is covered only '
             u'through the sub-registers named below.</p>' % (len(js), nsub))

    return u"%s\n%s\n%s\n    %s" % (BEGIN, intro, u"\n".join(out), END)


def _section_body(html, sec):
    """Return (start, end) of a section's body: everything between its <h2> and
    the </div> that closes the section. The body contains nested <div>s, so the
    end is found by scanning forward to the next section and taking the last
    </div> before it -- not by a non-greedy match, which stops at the first
    inner </div> and silently truncates the replacement."""
    m = re.search(u'<h2><span class="sec-num">%s</span>[^<]*</h2>' % re.escape(sec), html)
    if not m:
        raise SystemExit("section %s not found in %s" % (sec, DOC))
    start = m.end()
    stops = [i for i in (html.find(u"<h2", start),
                         html.find(u'<div class="doc-footer"', start)) if i != -1]
    nxt = min(stops) if stops else len(html)
    close = html.rfind(u"</div>", start, nxt)
    if close == -1:
        raise SystemExit("cannot find the closing </div> of section %s" % sec)
    return start, close


def splice(html, sec, fragment, keep_lead=True):
    """keep_lead=False where the fragment generates the section's opening
    paragraph itself (2.2 states the jurisdiction count, which is data)."""
    start, end = _section_body(html, sec)
    body = html[start:end]
    if BEGIN in body:
        lead = body.split(BEGIN)[0] if keep_lead else u"\n    "
    elif keep_lead:
        # the first <p>...</p> is the hand-written lead-in; the rest is generated
        lead_m = re.match(u"\\s*(<p>.*?</p>)\\s*", body, re.S)
        lead = (u"\n    " + lead_m.group(1) + u"\n    ") if lead_m else u"\n    "
    else:
        lead = u"\n    "
    return html[:start] + lead + fragment + u"\n  " + html[end:]


PRICE_LIST = os.path.join(REPO, "docs", "SEPTEO_ANNEX_2A_PRICE_LIST.html")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    data = load()
    js = data["jurisdictions"]
    c = counts(js)
    total = len(js)

    frag_tiers = tiers_fragment(js)
    frag_juris = jurisdictions_fragment(js, data)

    if not (args.write or args.check):
        print(frag_tiers)
        print()
        print(frag_juris)
        return 0

    with io.open(DOC, encoding="utf-8") as fh:
        html = fh.read()

    if args.check:
        problems = []
        m = re.search(r"(\d+)\s+jurisdictions are covered", html)
        if not m:
            problems.append("cannot find the jurisdiction count sentence in Annex 2.2")
        elif int(m.group(1)) != total:
            problems.append("Annex 2.2 says %s jurisdictions, price_bands.json has %d"
                            % (m.group(1), total))
        # Compare the SET of names, not the count. On 14.09.2026 the tier counts
        # matched by coincidence while the underlying sets differed, and a count
        # check passed on data that was wrong.
        rendered = set(re.findall(r'<span class="chip(?: stp| sub)?">([^<]+)<b>', html))
        expected = set(v["en"] for v in js.values())
        for entries in (data.get("subJurisdictions") or {}).values():
            expected |= set(e["en"] for e in entries)
        missing = sorted(expected - rendered)
        extra = sorted(rendered - expected)
        if missing:
            problems.append("Annex 2.2 is missing %d of %d jurisdictions: %s"
                            % (len(missing), len(expected), ", ".join(missing[:8])))
        if extra:
            problems.append("Annex 2.2 renders %d names not in the data: %s"
                            % (len(extra), ", ".join(extra[:8])))
        for tier in ("A", "B", "C", "D"):
            cost, _ = TIER_COST[tier]
            pat = (r'<td class="klass">%s</td><td class="price">%s &euro;</td>'
                   r'<td class="price soft">[^<]*</td><td class="price">(\d+)</td>'
                   % (tier, re.escape(cost)))
            mm = re.search(pat, html)
            if not mm:
                problems.append("tier %s row missing, reformatted, or its "
                                "procurement cost changed" % tier)
            elif int(mm.group(1)) != c[tier]:
                problems.append("tier %s says %s jurisdictions, data has %d"
                                % (tier, mm.group(1), c[tier]))

        if problems:
            print("DRIFT between price_bands.json and Annex 2:")
            for p in problems:
                print("  - " + p)
            return 1
        print("Annex 2 matches price_bands.json (%d jurisdictions, %s)"
              % (total, dict(c)))
        return 0

    html = splice(html, "2.1", frag_tiers)
    html = splice(html, "2.2", frag_juris, keep_lead=False)
    with io.open(DOC, "w", encoding="utf-8") as fh:
        fh.write(html)
    print("Annex 2 regenerated: %d jurisdictions, %s" % (total, dict(c)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
