# -*- coding: utf-8 -*-
"""Author curation/ubo_registry_intelligence.json — round-1 fast pass, EU-27 + GB/CH/NO/LI.

Sibling of curation/registry_intelligence.json: that one answers "can we reach the COMPANY
register directly", this one answers the same question for the BENEFICIAL-OWNERSHIP register,
which is a different register, a different legal basis and a different access regime.

Run: python scripts/build_ubo_intelligence.py  ->  curation/ubo_registry_intelligence.json
"""
import os, json
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "curation", "ubo_registry_intelligence.json")

TI = {"basis": "Transparency International — 'Countdown to new EU beneficial ownership rules', field-tested access in 14 MS (Sept 2025)",
      "url": "https://www.transparency.org/en/news/countdown-to-new-eu-beneficial-ownership-rules", "retrieved": "2026-08-20"}
TG = {"basis": "Topograph — 'UBO register access in Europe: a country-by-country reality check' (vendor blog, hands-on detail; SECONDARY)",
      "url": "https://www.topograph.co/blog/ubo-register-access-in-europe", "retrieved": "2026-08-20"}
KY = {"basis": "Kyckr — 'EU UBO Register Access for Obliged Entities (2026 Guide)' (vendor blog; SECONDARY)",
      "url": "https://kyckr.com/guides-and-reports/eu-ubo-register-access-for-obliged-entities-2025", "retrieved": "2026-08-20"}
BORIS_SRC = {"basis": "European e-Justice Portal — Beneficial ownership registers interconnection system (BORIS)",
             "url": "https://e-justice.europa.eu/topics/registers-business-insolvency-land/beneficial-ownership-registers-interconnection-system-boris_en", "retrieved": "2026-08-20"}
AMLD6 = {"basis": "Directive (EU) 2024/1640 (AMLD6), Art. 11-15 — register access rules",
         "url": "https://eur-lex.europa.eu/eli/dir/2024/1640/oj/eng", "retrieved": "2026-08-20"}
KVK = {"basis": "KVK (OFFICIAL) — 'Access to UBO Register for vennootschappen easier', reopening 1 April 2026",
       "url": "https://www.kvk.nl/en/ubo/ubo-access-expanded/", "retrieved": "2026-08-20"}
INHOUSE_DK = {"basis": "IN-HOUSE, measured: registry-access/DK_CVR/NOTIZ.md — S2S access granted 04.08.2026; cvr-re carries 601,877 'REELLE EJERE' records",
              "url": "https://distribution.virk.dk:8443/cvr-re/_search", "retrieved": "2026-08-05"}
INHOUSE_EE = {"basis": "IN-HOUSE, measured 2026-08-20: the BO query returns HTTP 303 to auth.rik.ee (idcard/mid/smartid) — no longer anonymous",
              "url": "https://ariregister.rik.ee/eng/beneficial_owners_query", "retrieved": "2026-08-20"}
MX = {"basis": "IN-HOUSE: jurisdiction_matrix.json (KYC.com catalogue, 217 jurisdictions) — only EE, MT, KH, GG list a beneficial-owner DOCUMENT",
      "url": "file://betterco-worldwide/jurisdiction_matrix.json", "retrieved": "2026-08-20"}


def R(j, **kw):
    d = dict(jurisdiction=j, registerName=None, registerBody=None, registerUrl=None,
             separateRegister=True, accessRegime=None, whoCanAccess=None,
             foreignAccess=None, credentials=None, machineAccess="none",
             delivers=["data"], documentViaApi=False, cost={"model": "unknown", "detail": ""},
             boris="unclear", vendorToday="shareholder data only (no UBO-register document)",
             notes="", confidence="medium", sources=[], verdict={})
    d.update(kw)
    return d


ROWS = [
    R("AT",
      registerName="Register der wirtschaftlichen Eigentuemer (WiEReG)",
      registerBody="Bundesministerium fuer Finanzen (Registerbehoerde)",
      registerUrl="https://www.bmf.gv.at/themen/betrugsbekaempfung/wirtschaftliche-eigentuemer-register.html",
      accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities under WiEReG, and applicants showing legitimate interest since 01.09.2023",
      foreignAccess="conditional",
      credentials="Application to the Registerbehoerde (wiereg-registerbehoerde@bmf.gv.at); TI's tester was asked for an employment contract; eID for the portal path",
      machineAccess="portal", delivers=["document"],
      cost={"model": "per_document", "detail": "~EUR 4 per simple extract, up to ~EUR 10 extended. TI measured EUR 4 and ~20 days to approval."},
      boris=True,
      notes="The extract carries a 'Vollstaendigkeitspruefung' completeness flag - a data-quality signal no other MS provides. Refusals are formal administrative decisions and therefore appealable. Austria is one of the few LIA states that demonstrably approves foreign applicants.",
      confidence="medium", sources=[TI, TG, KY],
      verdict={"tier": "direct_credentials", "reason": "LIA granted to foreign applicants in practice; per-extract fee; no API"}),

    R("BE",
      registerName="UBO-register / Registre UBO",
      registerBody="FOD Financien / SPF Finances - Algemene Administratie van de Thesaurie",
      registerUrl="https://finance.belgium.be/en/E-services/ubo-register",
      accessRegime="legitimate_interest",
      whoCanAccess="Authorities, Belgian AML-obliged entities and legitimate-interest applicants; public access withdrawn Nov 2022",
      foreignAccess="no",
      credentials="Belgian legal presence in practice: FPS Finance whitelisting, document submission and (per Topograph) a video call. ForReg credentials only cover filing your own entity, not third-party lookups.",
      machineAccess="manual", delivers=["document"],
      cost={"model": "free", "detail": "No fee reported. TI: free, response in under a week where granted."},
      boris=True,
      notes="SOURCE CONFLICT: TI obtained email-based access in under a week; Topograph reports Belgian establishment is required. Both can hold if the email path is open to EU obliged entities but not to a foreign software vendor. Our own BE dossier (docs/REGISTRY_ACCESS_BE_IL_2026-07-30.md) covers the COMPANY register only - the UBO register was never tested. Needs the dossier treatment.",
      confidence="low", sources=[TI, TG, KY],
      verdict={"tier": "customer_credentials", "reason": "access tied to Belgian obliged-entity status; no API"}),

    R("BG",
      registerName="Targovski registar / registar BULSTAT (UBO declarations)",
      registerBody="Agenciya po vpisvaniyata (Registry Agency)",
      registerUrl="https://portal.registryagency.bg/", separateRegister=False,
      accessRegime="public_local_credentials",
      whoCanAccess="Basic register data public; UBO detail behind a Bulgarian qualified electronic signature",
      foreignAccess="no", credentials="Bulgarian qualified electronic signature (KEP)",
      machineAccess="portal", delivers=["data"],
      cost={"model": "mixed", "detail": "Basic search free; certified extracts fee-based (not verified)"},
      notes="UBO data sits INSIDE the commercial register rather than in a separate one, so our existing BG company-register route may already carry part of it. Untested, single secondary source.",
      confidence="low", sources=[KY, TG],
      verdict={"tier": "customer_credentials", "reason": "UBO detail gated behind a Bulgarian e-signature"}),

    R("HR",
      registerName="Registar stvarnih vlasnika",
      registerBody="Financijska agencija (FINA) / Ministarstvo financija",
      registerUrl="https://rsv.fina.hr/", accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities, legitimate interest; sign-in through the national NIAS identity system",
      foreignAccess="no", credentials="NIAS (Croatian national eID) - residents and local entities only",
      machineAccess="portal", delivers=["data"],
      cost={"model": "free", "detail": "Free where access is granted"},
      notes="Named by both secondary sources as a national-credential lock. Not tested.",
      confidence="low", sources=[KY, TG],
      verdict={"tier": "customer_credentials", "reason": "NIAS eID cannot be obtained by a foreign company"}),

    R("CY",
      registerName="Register of Beneficial Owners",
      registerBody="Department of Registrar of Companies and Intellectual Property (DRCIP)",
      registerUrl="https://www.companies.gov.cy/en/business-entities/ubo-register",
      accessRegime="obliged_entities_only",
      whoCanAccess="Competent authorities and obliged entities; public access ceased 03.01.2023 after the CJEU ruling",
      foreignAccess="no", credentials="Cypriot authentication plus obliged-entity status",
      machineAccess="portal", delivers=["data"],
      cost={"model": "unknown", "detail": "Not published for the restricted channel"},
      notes="Cyprus has run the register on and off since 2023. Any published status here is perishable - re-check before quoting.",
      confidence="low", sources=[KY, TG],
      verdict={"tier": "closed", "reason": "authorities and local obliged entities only"}),

    R("CZ",
      registerName="Evidence skutecnych majitelu (ESM)",
      registerBody="Ministerstvo spravedlnosti - municipal courts",
      registerUrl="https://esm.justice.cz/", accessRegime="closed",
      whoCanAccess="Partial public access ended December 2025; access reverted to a court-application model",
      foreignAccess="no", credentials="Court application",
      machineAccess="none", delivers=["document"],
      cost={"model": "unknown", "detail": "Court fee, not verified"},
      notes="The clearest REGRESSION in the dataset: Czechia had a working partial public channel and closed it. Both secondary sources agree on the December 2025 date; the replacement procedure is unverified.",
      confidence="low", sources=[KY, TG],
      verdict={"tier": "closed", "reason": "public channel withdrawn Dec 2025, court application only"}),

    R("DK",
      registerName="Reelle ejere (inside CVR)",
      registerBody="Erhvervsstyrelsen (Danish Business Authority)",
      registerUrl="https://distribution.virk.dk:8443/cvr-re", separateRegister=False,
      accessRegime="public_via_s2s",
      whoCanAccess="Formally LIA since 01.09.2025 - but the system-to-system data feed was granted to us, a German non-obliged company, on written application",
      foreignAccess="yes",
      credentials="System-til-system application to Erhvervsstyrelsen plus a Tro-og-loveerklaering; HTTP Basic credentials issued. No MitID required.",
      machineAccess="api", delivers=["data"],
      cost={"model": "free", "detail": "Free. No per-search or per-record charge. Only the articles of association (vedtaegter) are excluded and must be ordered for a fee."},
      boris=True, vendorToday="vendor not needed - we source DK ourselves",
      notes="PROVEN IN-HOUSE AND LIVE. Applied 31.07.2026, credentials 04.08.2026, UBO index confirmed by Erhvervsstyrelsen 05.08.2026. cvr-re carries 601,877 REELLE EJERE records with capital AND voting-right percentages held separately. TRAP: the Danish substitute UBO, BETYDELIG_INDFLYDELSE_VIA_ROLLE ('reel ejer som udpeget daglig ledelse'), records management because no natural person crosses 25% - that is not a beneficial owner and must not be presented as one. This row is the counter-example to the whole 'Europe is closed' narrative: a plain written application to the registry succeeded where the eID/LIA front door would have failed.",
      confidence="high", sources=[INHOUSE_DK, TG, TI],
      verdict={"tier": "open_direct", "reason": "live free S2S API delivering UBO data - already in production"}),

    R("EE",
      registerName="Tegelikud kasusaajad (e-Aeriregister)",
      registerBody="Registrite ja Infosuesteemide Keskus (RIK)",
      registerUrl="https://ariregister.rik.ee/eng/beneficial_owners_query", separateRegister=False,
      accessRegime="public_local_credentials",
      whoCanAccess="Was fully public and free. Measured 2026-08-20: the BO query now forces authentication (ID-card / Mobile-ID / Smart-ID). An amendment removes BO data from the open-data files and restricts individual queries and API services from ~July 2026.",
      foreignAccess="conditional",
      credentials="Estonian eID means. Smart-ID is obtainable by some non-residents - the only realistic foreign path.",
      machineAccess="api", delivers=["data", "document"], documentViaApi=True,
      cost={"model": "free", "detail": "Register data free since the 2023 open-data reform; BO data now being pulled out of the open-data set"},
      boris=True, vendorToday="KYC.com lists a 'Beneficial owners' DOCUMENT for EE",
      notes="THE HEADLINE CHANGE. Estonia was the EU's most open UBO register and every published comparison still calls it 'fully public'. That is now outdated - we measured the auth redirect ourselves. Because our vendor lists an EE beneficial-owner document, we have a fallback if the direct route closes entirely.",
      confidence="medium", sources=[INHOUSE_EE, TG, MX],
      verdict={"tier": "direct_credentials", "reason": "API is free but the BO endpoint now needs Estonian eID and open data is being withdrawn"}),

    R("FI",
      registerName="Tosiasialliset edunsaajat",
      registerBody="Patentti- ja rekisterihallitus (PRH)",
      registerUrl="https://www.prh.fi/en/kaupparekisteri/beneficial-owners.html",
      accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities and legitimate-interest applicants under a data-use contract",
      foreignAccess="conditional", credentials="Data-use contract with PRH; foreign banks accepted with justification",
      machineAccess="manual", delivers=["document"],
      cost={"model": "contract", "detail": "Topograph: EUR 200 up front plus EUR 0.90 per extract. TI measured EUR 7-200. Contract-based, so the real number is negotiated."},
      notes="COVERAGE GAP no other MS has: the register covers private limited companies (Oy) only - no data for Oyj, associations, foundations or sole traders. Sources disagree on price; the contract is the thing to negotiate.",
      confidence="medium", sources=[TG, TI, KY],
      verdict={"tier": "direct_credentials", "reason": "contractual access open to foreign institutions, but no API and an entity-type coverage gap"}),

    R("FR",
      registerName="Registre des beneficiaires effectifs (RBE)",
      registerBody="INPI (since the RNE transfer)",
      registerUrl="https://data.inpi.fr/", accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities, legitimate interest. Public access withdrawn after the CJEU ruling.",
      foreignAccess="conditional",
      credentials="INPI account plus AML documentation plus a French SIREN; full BO fields require the ROLE_RBE_BENEFICIAL_OWNERS entitlement on the DATA INPI API",
      machineAccess="api", delivers=["data"],
      boris=True,
      cost={"model": "free", "detail": "Free once approved"},
      notes="STRATEGICALLY THE MOST IMPORTANT ROW. France is the only large MS with a real UBO API - and we already run an INPI client for the RNE (inpi_client.py, docs/FR_INPI_INTEGRATION.md). The blocker is the entitlement, not the plumbing. The SIREN requirement means a cross-border mandate needs a French registration. ACTION: ask INPI whether ROLE_RBE_BENEFICIAL_OWNERS can be granted on our existing account.",
      confidence="medium", sources=[TG, TI, KY],
      verdict={"tier": "direct_credentials", "reason": "real API and we already hold an INPI account; needs the RBE entitlement and likely a French SIREN"}),

    R("DE",
      registerName="Transparenzregister",
      registerBody="Bundesanzeiger Verlag (beliehen), supervised by the BVA",
      registerUrl="https://www.transparenzregister.de/",
      accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities under the GwG, and legitimate-interest applicants since the CJEU ruling",
      foreignAccess="conditional", credentials="Online registration, German-language process, written justification of legal need",
      machineAccess="portal", delivers=["document"],
      cost={"model": "per_document", "detail": "~EUR 1.65 per extract (TI). Registration free."},
      boris=True, vendorToday="OUT OF KYC.COM SCOPE - we source Germany ourselves",
      notes="A build row, not a buy row. Processing time is the barrier, not price: TI had no response since March 2025 and Topograph reports an application pending over a year against official guidance of 'several weeks'. Moody's/kompany advertises a Transparenzregister integration, which is evidence the channel can be made to work commercially.",
      confidence="medium", sources=[TI, TG, KY],
      verdict={"tier": "direct_credentials", "reason": "cheap and open in principle to obliged entities; the queue is the barrier"}),

    R("GR",
      registerName="Kentriko Mitroo Pragmatikon Dikaiouchon (GEMI)",
      registerBody="Ypourgeio Oikonomikon / GEMI",
      registerUrl="https://www.businessportal.gr/", accessRegime="obliged_entities_only",
      whoCanAccess="Authorities and local obliged entities; public access suspended 01.12.2022",
      foreignAccess="no", credentials="TAXISnet / Greek national authentication",
      machineAccess="portal", delivers=["data"],
      cost={"model": "unknown", "detail": "Not published"},
      boris=True,
      notes="Reported among the countries with searchable BORIS records while the domestic channel is closed - the same contradiction as Liechtenstein. Worth one probe if BORIS access is ever obtained.",
      confidence="low", sources=[KY, TG],
      verdict={"tier": "closed", "reason": "suspended for all but authorities and local obliged entities"}),

    R("HU",
      registerName="Tenyleges tulajdonosi nyilvantartas",
      registerBody="NAV / BISZ Zrt.",
      registerUrl="https://nav.gov.hu/", accessRegime="closed",
      whoCanAccess="Authorities; others must prove a family, legal, ownership or business tie to the target company",
      foreignAccess="no", credentials="Proof of a pre-existing connection to the target entity",
      machineAccess="none", delivers=["document"],
      cost={"model": "per_document", "detail": "~EUR 3.79 per extract (TI)"},
      notes="The criterion is circular: to look up who owns a company you must already show a link to its owners. TI waited four months against a stated 30-day limit and was refused. Treat as unavailable.",
      confidence="medium", sources=[TI, TG, KY],
      verdict={"tier": "closed", "reason": "circular criteria, applied to refuse in practice"}),

    R("IE",
      registerName="Register of Beneficial Ownership (RBO)",
      registerBody="Registrar of Beneficial Ownership (with the CRO)",
      registerUrl="https://rbo.gov.ie/", accessRegime="obliged_entities_only",
      whoCanAccess="Irish AML-designated persons via Form BOR4; legitimate-interest applicants via Form BOR5",
      foreignAccess="no", credentials="Irish designated-person status; paper/PDF forms",
      machineAccess="none", delivers=["document"],
      cost={"model": "free", "detail": "No fee reported"},
      notes="Ireland issued an outright refusal to TI, demanding proof that the target company was linked to convicted money launderers or to assets in high-risk countries. The BOR4 route does work - but only for an Irish designated person. A textbook customer-credential row.",
      confidence="medium", sources=[TI, TG, KY],
      verdict={"tier": "customer_credentials", "reason": "BOR4 access is reserved to Irish designated persons"}),

    R("IT",
      registerName="Registro dei titolari effettivi",
      registerBody="Camere di Commercio / InfoCamere (Registro Imprese)",
      registerUrl="https://www.registroimprese.it/", separateRegister=False,
      accessRegime="suspended",
      whoCanAccess="Nobody outside authorities pending the CJEU reference. A legitimate-interest basis exists on paper from January 2026 but the register is frozen.",
      foreignAccess="no", credentials="n/a while frozen",
      machineAccess="none", delivers=["document"],
      cost={"model": "unknown", "detail": "n/a while frozen"},
      notes="Italy built the register, the Consiglio di Stato suspended it and referred trust-access questions to the CJEU, and a March 2026 decree reportedly restarts the framework. We already hold a Telemaco/ABDO route to the Italian COMPANY register (docs/REGISTRY_ACCESS_IT_ES_LU_2026-07-30.md) and the UBO section would ride on the same access once it reopens. Highest-value row to re-check on a schedule.",
      confidence="medium", sources=[KY, TG],
      verdict={"tier": "closed", "reason": "register frozen pending a CJEU ruling"}),

    R("LV",
      registerName="Patiesa labuma guveji (Uznemumu registrs)",
      registerBody="Latvijas Republikas Uznemumu registrs",
      registerUrl="https://www.ur.gov.lv/", separateRegister=False,
      accessRegime="public",
      whoCanAccess="Everyone - Latvia decided explicitly to keep the register public after the CJEU ruling",
      foreignAccess="yes", credentials="None for the public view; login needed to download supporting documents",
      machineAccess="portal", delivers=["data", "document"],
      cost={"model": "free", "detail": "Free public view of current UBO data; free downloadable UBO statements"},
      boris=True,
      notes="One of only three genuinely open registers left in the EU, and TI independently confirms it. There is no official bulk or API channel for UBO: the machine path is either a licensed Latvian redistributor or our own scraper. New national requirements were announced for 2026 - check whether they touch access or only filing duties.",
      confidence="medium", sources=[TI, TG, KY],
      verdict={"tier": "open_direct", "reason": "public and free; machine access still has to be built or licensed"}),

    R("LT",
      registerName="JANGIS - naudos gaveju posistemis",
      registerBody="Registru centras",
      registerUrl="https://www.registrucentras.lt/", accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities and legitimate-interest applicants; TI reports both general and case-by-case access exist",
      foreignAccess="no", credentials="Lithuanian ID card or mobile signature; Lithuania-based entities in practice",
      machineAccess="api", delivers=["data"],
      cost={"model": "per_query", "detail": "EUR 0.03-2.93 per query; bulk querying available to holders of access"},
      vendorToday="NONE - LT is absent from jurisdiction_matrix.json entirely",
      notes="TWO PROBLEMS. (1) Access needs Lithuanian eID. (2) LITHUANIA IS NOT IN OUR VENDOR MATRIX AT ALL - so we have neither a direct route nor a vendor route today. TI also flagged a 20-plus question balancing form available only in Lithuanian. At EUR 0.03 per query it would be the cheapest source in Europe if the door could be opened.",
      confidence="medium", sources=[TI, TG, MX],
      verdict={"tier": "customer_credentials", "reason": "cheap and bulk-capable but locked behind Lithuanian eID - and no vendor fallback"}),

    R("LU",
      registerName="Registre des beneficiaires effectifs (RBE)",
      registerBody="Luxembourg Business Registers (LBR)",
      registerUrl="https://www.lbr.lu/", accessRegime="legitimate_interest",
      whoCanAccess="Article 2 professionals have a standing channel under Circular LBR 22/01; everyone else applies case by case",
      foreignAccess="conditional", credentials="Article 2 professional status, or a manual application per company",
      machineAccess="manual", delivers=["document"],
      cost={"model": "per_document", "detail": "EUR 5 per request"},
      boris=True,
      notes="Partly suspended since July 2022 and still not fully operational. NOTE THE CONTRAST with our LU company-register finding: the LBR API is confirmed to deliver documents but costs EUR 5,000/year (docs/REGISTRY_ACCESS_IT_ES_LU_2026-07-30.md). Whether that paid API also carries the RBE is UNVERIFIED and is the cheapest open question in this dataset - we already have the LBR contact path. LU sits in the High price band together with FR, our most expensive pair.",
      confidence="medium", sources=[TG, TI, KY],
      verdict={"tier": "direct_credentials", "reason": "manual today; the paid LBR API may already cover it - unverified"}),

    R("MT",
      registerName="Register of Beneficial Owners",
      registerBody="Malta Business Registry (MBR)",
      registerUrl="https://mbr.mt/", accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities and legitimate interest; email requests accepted; open to EU citizens holding a digital ID",
      foreignAccess="yes", credentials="EU digital ID, or an AML-justified email request",
      machineAccess="api", delivers=["document"], documentViaApi=True,
      cost={"model": "contract", "detail": "EUR 5 per scanned extract on the manual path; API subscription reported at EUR 450/year, pending validation"},
      boris=True, vendorToday="KYC.com lists a 'Beneficial Owner Printout' DOCUMENT for MT",
      notes="One of only two EU/EEA jurisdictions where our vendor already delivers a UBO-register DOCUMENT, so Malta is covered today. The EUR 450/year API only pays off at volume.",
      confidence="medium", sources=[TG, KY, MX],
      verdict={"tier": "direct_credentials", "reason": "cheapest API subscription in the set - and already covered by the vendor"}),

    R("NL",
      registerName="UBO-register",
      registerBody="Kamer van Koophandel (KVK)",
      registerUrl="https://www.kvk.nl/en/ubo/ubo-access-expanded/",
      accessRegime="obliged_entities_only",
      whoCanAccess="Recognised Wwft and sanctions institutions since 01.04.2026: civil-law notaries, banks, trust offices, DNB-licensed life insurers, AFM-licensed investment firms and credit providers. Notification runs through the sector organisations.",
      foreignAccess="no",
      credentials="Recognition as a Dutch Wwft/sanctions institution; eHerkenning for the web-ordering path from Q2 2026",
      machineAccess="api", delivers=["document"], documentViaApi=True,
      cost={"model": "unknown", "detail": "Not published on the access page"},
      boris=True,
      notes="THE MOST CONCRETE NEW OPPORTUNITY, and the only fully official source in this dataset. Shut in Nov 2022, reopened 01.04.2026 with a digitally certified UBO extract (PDF) orderable BY API; a JSON 'UBO API 2.0' is planned for ~2027. The catch is the eligibility list - a German software vendor is not on it. This is the archetype for the customer-credential model: the customer is the Wwft institution, we are the pipe. KVK's page does not address third-party or foreign access, so ASK KVK directly.",
      confidence="high", sources=[KVK, TG, KY],
      verdict={"tier": "customer_credentials", "reason": "certified extract via API exists, but only recognised Dutch Wwft institutions are eligible"}),

    R("PL",
      registerName="Centralny Rejestr Beneficjentow Rzeczywistych (CRBR)",
      registerBody="Ministerstwo Finansow",
      registerUrl="https://crbr.podatki.gov.pl/", accessRegime="public",
      whoCanAccess="Everyone. No registration and no fee - Poland kept the register fully public.",
      foreignAccess="yes", credentials="None",
      machineAccess="portal", delivers=["data", "document"],
      cost={"model": "free", "detail": "Free, unlimited public search"},
      notes="Legally the easiest UBO source in the EU and technically the most annoying: there is NO official API. Access is portal-only, so everyone operating at scale either scrapes CRBR or buys a Polish redistributor such as Transparent Data. Our commercial-register intelligence already rates PL a strong go-direct; the UBO piece is a separate, unofficial build.",
      confidence="medium", sources=[TG, KY],
      verdict={"tier": "open_direct", "reason": "fully public and free, but needs a scraper because there is no official API"}),

    R("PT",
      registerName="Registo Central do Beneficiario Efetivo (RCBE)",
      registerBody="Instituto dos Registos e do Notariado (IRN)",
      registerUrl="https://rcbe.justica.gov.pt/", accessRegime="public_local_credentials",
      whoCanAccess="Was public; a legitimate-interest decree of October 2025 is not yet deployed. Access in practice needs a Portuguese Cartao de Cidadao.",
      foreignAccess="no", credentials="Cartao de Cidadao / Chave Movel Digital",
      machineAccess="portal", delivers=["data"],
      cost={"model": "free", "detail": "Free where accessible"},
      notes="In transition: the new access framework is announced but not live. Re-check once the decree is deployed.",
      confidence="low", sources=[KY, TG],
      verdict={"tier": "customer_credentials", "reason": "Portuguese citizen-card authentication only"}),

    R("RO",
      registerName="Registrul beneficiarilor reali",
      registerBody="Oficiul National al Registrului Comertului (ONRC)",
      registerUrl="https://www.onrc.ro/", separateRegister=False,
      accessRegime="public_local_credentials",
      whoCanAccess="Public in principle and transitioning to legitimate interest; requests are filed with ONRC",
      foreignAccess="conditional", credentials="Romanian qualified electronic signature for the online channel",
      machineAccess="portal", delivers=["document"],
      cost={"model": "per_document", "detail": "Fee-based; ONRC restricts API-based resale"},
      notes="Both sources agree ONRC restricts redistribution - which matters more to us than the fee, because our product IS redistribution. Same pattern we already found in Italy, where standard Telemaco forbids passing data to customers without an operator contract. Verify the licence terms before building.",
      confidence="low", sources=[KY, TG],
      verdict={"tier": "customer_credentials", "reason": "local e-signature plus explicit resale restrictions"}),

    R("SK",
      registerName="Register pravnickych osob - konecny uzivatel vyhod",
      registerBody="Statisticky urad SR (the separate RPVS is run by the Ministry of Justice)",
      registerUrl="https://rpo.statistics.sk/", accessRegime="closed",
      whoCanAccess="Authorities only - public access to beneficial-ownership data was discontinued on 10.07.2025, the exact AMLD6 Art. 74 date",
      foreignAccess="no", credentials="n/a",
      machineAccess="none", delivers=["data"],
      cost={"model": "free", "detail": "n/a"},
      notes="PARTIAL WORKAROUND: the Register partnerov verejneho sektora (RPVS) is a DIFFERENT, still-public register that discloses verified beneficial owners - but only for entities doing business with the Slovak public sector. Useful for a subset, useless as general coverage. Slovakia is rated a strong go-direct for the company register, so the split between its two registers is unusually sharp.",
      confidence="medium", sources=[KY, TG],
      verdict={"tier": "closed", "reason": "public UBO access withdrawn July 2025; only the public-sector RPVS subset remains"}),

    R("SI",
      registerName="Register dejanskih lastnikov (RDL)",
      registerBody="AJPES",
      registerUrl="https://www.ajpes.si/", accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities and legitimate-interest applicants; AJPES applies a broad reading of AML justification",
      foreignAccess="conditional", credentials="Email application with supporting documents; eID for the portal path",
      machineAccess="manual", delivers=["data"],
      cost={"model": "free", "detail": "Free"},
      notes="Both secondary sources describe Slovenia as one of the more cooperative LIA regimes, and it costs nothing. Cheap to test - a good candidate for an early application alongside Austria.",
      confidence="low", sources=[TI, TG, KY],
      verdict={"tier": "direct_credentials", "reason": "free, manual, and reportedly broad in granting AML-justified access"}),

    R("ES",
      registerName="Registro Central de Titularidades Reales (RCTIR)",
      registerBody="Ministerio de Justicia (alongside the notarial Base de Datos de Titularidad Real of the Consejo General del Notariado)",
      registerUrl="https://www.mjusticia.gob.es/", accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities, legitimate interest - but TI found the access channel entirely non-functional",
      foreignAccess="no", credentials="DNI/NIE or a Spanish electronic certificate; Spanish-language process",
      machineAccess="none", delivers=["data"],
      cost={"model": "free", "detail": "Free today, fees announced"},
      notes="TI's tester waited about six months and called the eID path entirely non-functional. Spain has TWO sources: the state RCTIR and the notaries' own titularidad real database, which the notarial network sells to obliged entities - that second path is what Spanish banks actually use and it is NOT assessed here. Our ES company-register dossier already found that a certificado electronico or Cl@ve is mandatory even for the company register - the same wall.",
      confidence="medium", sources=[TI, TG, KY],
      verdict={"tier": "closed", "reason": "nominally LIA, non-functional in practice for a foreign applicant"}),

    R("SE",
      registerName="Registret over verkliga huvudman",
      registerBody="Bolagsverket",
      registerUrl="https://bolagsverket.se/", accessRegime="legitimate_interest",
      whoCanAccess="Authorities, obliged entities and legitimate interest; TI got immediate access via eID and describes the process as clear",
      foreignAccess="conditional", credentials="Swedish BankID for instant access; email request otherwise, answered in days",
      machineAccess="manual", delivers=["document"],
      cost={"model": "per_document", "detail": "Topograph: SEK 120 per extract. TI recorded no fee. Discrepancy unresolved."},
      notes="DATA-MODEL TRAP: Sweden records 'Omfattning' - the extent of control in bands - not an ownership percentage, and several UBOs can each show the maximum band. Any normalisation into a percentage model will be wrong. Output is PDF and has to be parsed. Otherwise one of the smoothest LIA processes tested.",
      confidence="medium", sources=[TI, TG, KY],
      verdict={"tier": "direct_credentials", "reason": "clear process with an email path for foreigners; PDF only, no API"}),

    R("GB",
      registerName="People with Significant Control (PSC) register",
      registerBody="Companies House",
      registerUrl="https://developer.company-information.service.gov.uk/",
      accessRegime="public",
      whoCanAccess="Everyone. Free REST API and bulk downloads, no credentials beyond a free API key.",
      foreignAccess="yes", credentials="Free Companies House API key",
      machineAccess="api", delivers=["data"],
      cost={"model": "free", "detail": "Free API, free bulk product data"},
      boris=False, vendorToday="we already run a GB connector",
      notes="THE BENCHMARK, and proof that open UBO data is technically trivial once it is legally permitted. Not EU, so untouched by the CJEU ruling. QUALITY CAVEAT: historically self-declared and unverified - roughly a fifth of records miss an individual owner and a fifth sum above 100%. The ECCTA identity-verification reform is closing that gap.",
      confidence="high", sources=[TG, KY],
      verdict={"tier": "open_direct", "reason": "free public REST API and bulk data - nothing in Europe comes close"}),

    R("CH",
      registerName="none yet - Transparenzregister under the new LETA/TJPG law",
      registerBody="Eidgenoessisches Justiz- und Polizeidepartement; delivery expected via EasyGov",
      registerUrl="https://www.easygov.swiss/", accessRegime="none",
      whoCanAccess="Nobody today. The law adopted in September 2025 creates a register expected in autumn 2026, restricted to domestic authorities and Swiss financial intermediaries.",
      foreignAccess="no", credentials="n/a",
      machineAccess="none", delivers=[],
      cost={"model": "n/a", "detail": "Non-filing penalty reported up to CHF 500,000; access pricing unknown"},
      boris=False,
      notes="Switzerland has NO beneficial-ownership register at all right now. The honest answer to a customer asking for a Swiss UBO document is that it does not exist, and that when it does it will be closed to us. Ties directly to the open VR-Data CH vendor question (docs/VRDATA_CH_ANSWER_2026-08-11.md): if a vendor claims a Swiss UBO source today, ask precisely what it is.",
      confidence="medium", sources=[TG],
      verdict={"tier": "none", "reason": "no register exists; the coming one is authorities-and-Swiss-banks only"}),

    R("NO",
      registerName="Register over reelle rettighetshavere",
      registerBody="Bronnoysundregistrene",
      registerUrl="https://www.brreg.no/", accessRegime="obliged_entities_only",
      whoCanAccess="Authorities and obliged entities. Filing became mandatory in July 2025. There is no public web interface at all.",
      foreignAccess="no", credentials="Norwegian obliged-entity status",
      machineAccess="api", delivers=["data"],
      cost={"model": "unknown", "detail": "Not published"},
      boris=True,
      notes="Inverted from everywhere else: Norway built an API-ONLY register with no portal. The data is machine-shaped and the entitlement is the wall. The public Bronnoysund business-register API - which we can already use - does NOT expose the UBO data.",
      confidence="medium", sources=[TG],
      verdict={"tier": "customer_credentials", "reason": "API-only register restricted to authorities and obliged entities"}),

    R("LI",
      registerName="Verzeichnis der wirtschaftlich berechtigten Personen (VwbP)",
      registerBody="Amt fuer Justiz (AJU)",
      registerUrl="https://www.llv.li/", accessRegime="authorities_only",
      whoCanAccess="Authorities and the FIU; banks apply per entity",
      foreignAccess="no", credentials="n/a",
      machineAccess="none", delivers=["document"],
      cost={"model": "unknown", "detail": "Not published"},
      boris=True,
      notes="Extracts explicitly carry no public reliance - the authority does not verify the data. Liechtenstein is connected to BORIS while being closed domestically, the same contradiction as Greece.",
      confidence="low", sources=[TG],
      verdict={"tier": "closed", "reason": "authorities only, with per-entity applications for banks"}),
]

MARKET = {
    "question": "Is there a data source that aggregates EU UBO registers?",
    "answer": "No usable one. Three archetypes exist and each fails a different requirement.",
    "archetypes": [
        {"name": "BORIS - the official EU interconnection",
         "operator": "European Commission / e-Justice Portal",
         "whatItIs": "The legally mandated interconnection of national UBO registers.",
         "whyItFails": "Access still runs through your own national register, so a gated home register gates BORIS too. Reported coverage is 17 of 30 EU/EEA states; output is a static PDF extract one company at a time, with no API and no bulk download.",
         "sources": [BORIS_SRC, TI, TG]},
        {"name": "Derived / inferred ownership graphs",
         "operator": "Moody's (Orbis, Bureau van Dijk), Dun & Bradstreet, Sayari, LSEG World-Check UBO Check (which resells D&B or Sayari), Creditsafe",
         "whatItIs": "Global ownership networks computed by walking shareholding chains across company registers - LSEG cites 430m+ ownership connections across 220+ territories.",
         "whyItFails": "It is a calculation, not a filing. It answers 'who probably owns this' but cannot produce the register document an auditor asks for, and it is not what the UBO register says. Sayari itself reports 20-40% discrepancy against self-reported UBO questionnaires on high-risk counterparties.",
         "sources": [{"basis": "LSEG World-Check UBO Check data catalogue", "url": "https://www.lseg.com/en/data-catalogue/risk/worldcheck-data/ubo-check", "retrieved": "2026-08-20"},
                     {"basis": "Sayari - beneficial ownership for KYC", "url": "https://sayari.com/enterprise/kyc-beneficial-ownership/", "retrieved": "2026-08-20"}]},
        {"name": "Real-time official-register retrieval",
         "operator": "Moody's/kompany, Kyckr, Topograph, Zavia, Global Database",
         "whatItIs": "Fetch the actual official filing on request and time-stamp it. kompany advertises real-time access across 200+ jurisdictions with named integrations into the German Transparenzregister and the French INPI UBO register.",
         "whyItFails": "Their UBO-REGISTER coverage collapses to the handful of registers that are actually reachable, because they face exactly the same national access walls we do. Coverage claims of '200+ jurisdictions' describe COMPANY registers, not UBO registers.",
         "sources": [{"basis": "Moody's - kompany KYC API product page (real-time official sources)", "url": "https://www.moodys.com/web/en/us/kyc/products/kompany.html", "retrieved": "2026-08-20"},
                     {"basis": "Kyckr UBO Verify - extracts shareholder data from official filings", "url": "https://kyckr.com/guides-and-reports/eu-ubo-register-access-for-obliged-entities-2025", "retrieved": "2026-08-20"}]},
    ],
    "inHouseEvidence": "Our own vendor catalogue is the sharpest measurement available: across 217 jurisdictions in jurisdiction_matrix.json, only four list a beneficial-owner DOCUMENT (EE, MT, KH, GG) - two of them in our 31-country scope. Everything else labelled 'shareholders' or 'controlling' is company-register data, not a UBO-register filing.",
    "closedAggregator": "Open Ownership closed its transnational Open Ownership Register on 29 November 2024 after seven years; the republished open datasets remain at bods-data.openownership.org.",
    "regulatoryClock": {
        "cjeu": "Joined Cases C-37/20 and C-601/20 (WM and Sovim, 22 Nov 2022) struck down public access - the cause of every closure in this dataset.",
        "amld6": "Directive (EU) 2024/1640 Art. 11-15: obliged entities and legitimate-interest applicants regain access. Transposition of the register-access articles falls due 10 July 2026; the AMLR applies fully from 10 July 2027.",
        "reality": "As of Sept 2025 the Commission had opened infringement proceedings against 11 Member States for missing the July 2025 notification deadline. Do not plan on the 2026 dates holding.",
        "art13": "From 10 November 2026 registers must answer legitimate-interest requests within 12 working days, and approved applicants get 3-year certificates - the first provision that would make an automated pipeline realistic.",
        "sources": [AMLD6, TI],
    },
}

ACTIONS = [
    {"prio": 1, "who": "FR / INPI",
     "action": "Ask INPI whether ROLE_RBE_BENEFICIAL_OWNERS can be added to our EXISTING DATA INPI account, and whether a French SIREN is truly mandatory or only the default path.",
     "why": "France is the only large Member State with a real UBO API and we already run the client. This is the single highest-leverage question in the whole dataset, and it costs one email.",
     "cost": "one email"},
    {"prio": 2, "who": "LU / LBR",
     "action": "Ask LBR whether the EUR 5,000/year document API already covers the RBE, or only the company register.",
     "why": "We have already established the LBR contact path and the price. If the RBE rides on the same subscription, LU flips from manual-per-request to automated at no extra cost — and LU is in our most expensive price band.",
     "cost": "one email"},
    {"prio": 3, "who": "NL / KVK",
     "action": "Ask KVK whether a technical service provider may query the UBO API on behalf of a recognised Wwft institution, and what the fee model is.",
     "why": "The Dutch register reopened on 01.04.2026 with a certified extract available BY API — the cleanest new channel in Europe. Whether we can operate it for a customer decides if the customer-credential model works at all.",
     "cost": "one email"},
    {"prio": 4, "who": "AT + SI",
     "action": "File legitimate-interest applications. Both are documented as granting to foreign applicants; SI is free and AT costs ~EUR 4 per extract.",
     "why": "Cheapest way to convert two 'medium confidence' rows into measured fact, and to learn what the LIA process actually demands of a German applicant before we need it elsewhere.",
     "cost": "two applications, < EUR 50"},
    {"prio": 5, "who": "EE",
     "action": "Re-measure and decide: obtain Smart-ID, or fall back to the vendor's EE beneficial-owner document.",
     "why": "Estonia's BO query now forces eID and its open data is being withdrawn from ~July 2026. Every published market comparison still calls Estonia 'fully public' — including ones a customer may quote at us.",
     "cost": "measurement"},
    {"prio": 6, "who": "LT",
     "action": "Add Lithuania to the vendor matrix or find another route.",
     "why": "LT is missing from jurisdiction_matrix.json entirely, so we currently have NO route to Lithuania at all — neither direct nor vendor. That is a coverage hole, not a UBO problem.",
     "cost": "vendor question"},
    {"prio": 7, "who": "Product",
     "action": "Introduce UBO as a FOURTH document kind alongside Registerauszug / Gesellschaftsvertrag / Gesellschafterliste, with the existing via='data'|'document' distinction.",
     "why": "Our own research already found the Gesellschafterliste is effectively unavailable outside Germany. In most Member States the UBO register is the nearest legal substitute — but it is a different document with different evidential weight, and conflating the two would be wrong.",
     "cost": "modelling"},
    {"prio": 8, "who": "Data model",
     "action": "Do not normalise UBO into a single ownership percentage.",
     "why": "Sweden records bands of control ('Omfattning'), not percentages, and several UBOs can each show the maximum. Denmark records capital and voting rights separately, and marks management as a substitute UBO (BETYDELIG_INDFLYDELSE_VIA_ROLLE) when nobody crosses 25%. A single percentage field silently falsifies both.",
     "cost": "modelling"},
    {"prio": 9, "who": "Watchlist",
     "action": "Put IT, CH, NL, EE and the AMLD6 transposition tracker on a scheduled re-check.",
     "why": "Five of the 31 rows are mid-transition with dated triggers: IT pending a CJEU ruling, CH expecting a register in autumn 2026, NL adding a JSON API in 2027, EE closing open data in July 2026, and the Art. 13 twelve-working-day rule starting 10 November 2026.",
     "cost": "recurring"},
]

DATA = {
    "generated": "2026-08-20",
    "pass": "round-1-fast",
    "scope": "EU-27 + GB, CH, NO, LI (31 jurisdictions)",
    "note": ("FAST PASS. Verdicts lean on secondary sources - Transparency International's field test of 14 "
             "Member States (Sept 2025) and vendor research by Kyckr and Topograph (2026) - except where a row is "
             "marked IN-HOUSE or cites an official registry page. Rows at confidence 'low' must not be quoted to a "
             "customer before the dossier treatment used in docs/REGISTRY_ACCESS_*.md."),
    "market": MARKET,
    "actions": ACTIONS,
    "rows": ROWS,
}


def main():
    json.dump(DATA, open(OUT, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
    print("wrote", OUT, "rows:", len(ROWS))
    print("tiers:", Counter(r["verdict"]["tier"] for r in ROWS))
    print("confidence:", Counter(r["confidence"] for r in ROWS))


if __name__ == "__main__":
    main()
