# -*- coding: utf-8 -*-
"""Generate Annex 2.1 (price tiers) and Annex 2.2 (covered jurisdictions) of the
Septeo reseller agreement from curation/price_bands.json.

The annex used to be hand-edited, drifted from the data, and the drift was
invisible: on 14.09.2026 the tier counts matched by coincidence while the
underlying sets differed. Nothing in section 2.1 or 2.2 may be typed by hand
again -- edit the JSON, re-run this, and let --check fail the build if someone
does it anyway.

    python scripts/build_annex2.py --check     # exit 1 if the document drifted
    python scripts/build_annex2.py --write     # regenerate the two sections
    python scripts/build_annex2.py             # print the fragments

Procurement costs are the CONTRACTED per-case fees from the supply Order Form,
not the list prices on the coverage page. They live here because they are a
commercial term of our own, not a property of the coverage data.
"""
from __future__ import print_function

import argparse
import collections
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
BANDS = os.path.join(REPO, "curation", "price_bands.json")
DOC = os.path.join(REPO, "docs", "SEPTEO_RESELLER_AGREEMENT_2026-09-14.html")

# tier -> (contracted procurement cost, list price shown for information)
TIER_COST = {
    "A": ("10,80", "15,00"),
    "B": ("26,70", "35,00"),
    "C": ("54,50", "70,00"),
    "D": ("70,50", "90,00"),
}
BAND_TO_TIER = {"Low": "A", "Medium": "B", "High": "C", "Premium": "D"}

TIER_BLURB = {
    "A": "the general case &mdash; open national registers",
    "B": "registers charging a per-document fee",
    "C": "fee-heavy or court-administered registers",
    "D": "offshore registers with a special tariff",
}

# Jurisdictions priced individually rather than by tier.
#
# These are NOT all "direct routes". Until 15.09.2026 the annex said GB, DE and
# US were served by our own direct routes at 1,70 / 6,30 / 17,35 EUR -- but those
# three figures are the SUPPLIER's Home Band fees from our Order Form, not our
# own sourcing. Our own direct routes are DE (handelsregister), FR (INPI) and
# DK (CVR). The two facts were conflated; keep them apart here.
INDIVIDUAL = [("GB", "United Kingdom", "1,70"),
              ("DE", "Germany", "6,30"),
              ("US", "United States", "17,35")]
OWN_ROUTES = ["DE", "FR", "DK"]
MANUAL_SURCHARGE = "3,50"

STP15 = ["FR", "IT", "GB", "US", "ES", "DK", "NL", "LU", "CH", "IL",
         "JP", "BE", "KW", "SG", "HK"]

REGION_ORDER = ["Europe", "Americas", "Asia", "Middle East", "Africa", "Oceania"]

BEGIN = "<!-- BEGIN generated by scripts/build_annex2.py -- do not edit by hand -->"
END = "<!-- END generated -->"


def load():
    with io.open(BANDS, encoding="utf-8") as fh:
        return json.load(fh)


def tier_of(entry):
    return BAND_TO_TIER.get(entry["band"])


def counts(js):
    c = collections.Counter()
    for entry in js.values():
        t = tier_of(entry)
        if t:
            c[t] += 1
    return c


def tiers_fragment(js):
    """Annex 2.1 states the tier structure and the counts. It states NO amounts:
    those live in the confidential price list (decision, 15.09.2026), so that the
    contract does not carry a rate card that maps 1:1 onto the supplier's public
    bands and identifies both the supplier and our discount."""
    c = counts(js)
    untiered = sorted(cc for cc, e in js.items() if tier_of(e) is None)
    rows = []
    for tier in ("A", "B", "C", "D"):
        rows.append(
            u'          <tr><td class="klass">%s</td>'
            u'<td class="price">%d</td>'
            u'<td>%s</td></tr>' % (tier, c[tier], TIER_BLURB[tier]))

    individual = u", ".join(name for _, name, _ in INDIVIDUAL)

    note = u""
    if untiered:
        names = u", ".join(js[cc]["en"] for cc in untiered)
        note = (u'\n    <p><strong>%s is not on a tier.</strong> It has no single '
                u'national register: company records are filed with each state, and '
                u'availability is determined per state. It is priced individually in '
                u'the price list, and Annex&nbsp;2.2 marks it accordingly.</p>' % names)

    return u"""%(begin)s
    <div class="tablewrap">
      <table class="price-table">
        <thead><tr>
          <th>Tier</th>
          <th class="price">Jurisdictions</th>
          <th>Typical registers in this tier</th>
        </tr></thead>
        <tbody>
%(rows)s
        </tbody>
      </table>
    </div>
    <p><strong>%(individual)s</strong> are priced individually rather than by tier. A case that has to be worked manually carries a surcharge. All amounts are net of VAT and are stated in the price list in force (clause&nbsp;8.6).</p>%(note)s
    %(end)s""" % {
        "begin": BEGIN, "rows": u"\n".join(rows), "individual": individual,
        "note": note, "end": END,
    }


def jurisdictions_fragment(js):
    by_region = collections.defaultdict(list)
    for cc, e in js.items():
        by_region[e.get("region", "Other")].append((cc, e["en"], tier_of(e)))

    order = [r for r in REGION_ORDER if r in by_region]
    order += sorted(r for r in by_region if r not in REGION_ORDER)

    out = []
    for region in order:
        rows = sorted(by_region[region], key=lambda r: r[1])
        out.append(u'    <div class="reg-title">%s <span>%d</span></div>'
                   % (region, len(rows)))
        out.append(u'    <div class="chips">')
        for cc, name, tier in rows:
            cls = "chip stp" if cc in STP15 else "chip"
            label = tier if tier else "&mdash;"
            out.append(u'      <span class="%s">%s<b>%s</b></span>' % (cls, name, label))
        out.append(u'    </div>')

    intro = (u'    <p>%d jurisdictions are covered. The '
             u'<span class="chip stp inline">highlighted<b>&nbsp;</b></span> entries are '
             u"STP's fifteen priority jurisdictions; the letter is the price tier per "
             u'section&nbsp;2.1, and &mdash; marks a jurisdiction priced individually.</p>'
             % len(js))

    return u"%s\n%s\n%s\n    %s" % (BEGIN, intro, u"\n".join(out), END)


def _section_body(html, sec):
    """Return (start, end) of a section's body: everything between its <h2> and
    the </div> that closes the section. The body contains nested <div>s, so the
    end is found by scanning forward to the next section and taking the last
    </div> before it -- not by a non-greedy match, which stops at the first
    inner </div> and silently truncates the replacement."""
    m = re.search(u'<h2><span class="sec-num">%s</span>[^<]*</h2>' % re.escape(sec), html)
    if not m:
        raise SystemExit("section %s not found in %s" % (sec, DOC))
    start = m.end()
    stops = [i for i in (html.find(u"<h2", start),
                         html.find(u'<div class="doc-footer"', start)) if i != -1]
    nxt = min(stops) if stops else len(html)
    close = html.rfind(u"</div>", start, nxt)
    if close == -1:
        raise SystemExit("cannot find the closing </div> of section %s" % sec)
    return start, close


def splice(html, sec, fragment, keep_lead=True):
    """keep_lead=False where the fragment generates the section's opening
    paragraph itself (2.2 states the jurisdiction count, which is data)."""
    start, end = _section_body(html, sec)
    body = html[start:end]
    if BEGIN in body:
        lead = body.split(BEGIN)[0] if keep_lead else u"\n    "
    elif keep_lead:
        # the first <p>...</p> is the hand-written lead-in; the rest is generated
        lead_m = re.match(u"\\s*(<p>.*?</p>)\\s*", body, re.S)
        lead = (u"\n    " + lead_m.group(1) + u"\n    ") if lead_m else u"\n    "
    else:
        lead = u"\n    "
    return html[:start] + lead + fragment + u"\n  " + html[end:]


PRICE_LIST = os.path.join(REPO, "docs", "SEPTEO_ANNEX_2A_PRICE_LIST.html")


def write_price_list(js, data):
    """Annex 2a -- the amounts the Agreement deliberately omits.

    Kept as a separate document so it can be replaced without re-executing the
    Agreement and so its circulation can be limited -- but INCORPORATED and dated
    at signature, and amendable only under clause 8.6. Under clause 8.2 the
    procurement cost is an input to the settlement formula, so a schedule one
    party could change at will would be both a negotiation target and a
    Sec. 307 BGB risk in an AGB reading."""
    c = counts(js)
    rows = []
    for tier in ("A", "B", "C", "D"):
        cost, lst = TIER_COST[tier]
        rows.append(u'          <tr><td class="klass">%s</td>'
                    u'<td class="price">%s &euro;</td>'
                    u'<td class="price soft">%s &euro;</td>'
                    u'<td class="price">%d</td></tr>'
                    % (tier, cost, lst, c[tier]))
    ind = []
    for cc, name, price in INDIVIDUAL:
        how = ("own direct route" if cc in OWN_ROUTES
               else "supplier home band")
        ind.append(u'          <tr><td class="lead-col">%s</td>'
                   u'<td class="price">%s &euro;</td><td>%s</td></tr>'
                   % (name, price, how))
    own = u", ".join(js[cc]["en"] for cc in OWN_ROUTES if cc in js)
    retrieved = data.get("_meta", {}).get("retrieved", "")

    html = u"""<title>Annex 2a Price List</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<style>
  :root {{ --blue:#6895FF; --blue-light:#e8efff; --navy:#1a2340; --dark:#222233;
    --gray-600:#6b7280; --gray-400:#9ca3af; --gray-200:#e5e7eb; --gray-100:#f3f4f6;
    --gray-50:#f9fafb; --white:#ffffff; }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:'Montserrat',system-ui,sans-serif; color:var(--dark);
    background:var(--gray-100); padding:24px 16px 60px; }}
  .page {{ width:210mm; max-width:100%; min-height:297mm; margin:0 auto;
    background:var(--white); box-shadow:0 2px 20px rgba(0,0,0,.08);
    padding:25mm 22mm 20mm; }}
  @media (max-width:720px) {{ .page {{ padding:22px 18px 28px; min-height:0; }} }}
  .doc-header {{ display:flex; justify-content:space-between; align-items:flex-start;
    gap:16px; margin-bottom:6px; padding-bottom:14px; border-bottom:3px solid var(--blue); }}
  .doc-header h1 {{ font-size:26px; font-weight:800; color:var(--navy); line-height:1.15; }}
  .kicker {{ font-size:9px; font-weight:700; letter-spacing:1.5px; text-transform:uppercase;
    color:var(--blue); margin-bottom:5px; }}
  .doc-date {{ font-size:10px; color:var(--gray-600); text-align:right; margin:10px 0 18px; }}
  .section {{ margin-bottom:16px; }}
  .section h2 {{ font-size:13px; font-weight:700; color:var(--navy); padding-bottom:4px;
    border-bottom:2px solid var(--blue); margin-bottom:9px; }}
  .sec-num {{ color:var(--blue); margin-right:5px; }}
  .section p {{ font-size:10.5px; line-height:1.7; margin-bottom:8px; }}
  .section strong {{ font-weight:700; color:var(--navy); }}
  .tablewrap {{ overflow-x:auto; margin:4px 0 10px; }}
  .price-table {{ width:100%; border-collapse:collapse; font-size:10.5px; }}
  .price-table thead th {{ font-size:8.5px; font-weight:700; text-transform:uppercase;
    letter-spacing:.5px; color:var(--white); background:var(--navy); padding:7px 9px;
    text-align:left; }}
  .price-table tbody tr {{ border-bottom:1px solid var(--gray-100); }}
  .price-table tbody td {{ padding:6px 9px; vertical-align:top; }}
  .price-table td.price, .price-table th.price {{ text-align:right; white-space:nowrap;
    font-variant-numeric:tabular-nums; font-weight:700; }}
  .price-table td.soft {{ color:var(--gray-400); font-weight:500; }}
  .price-table td.klass {{ font-weight:800; color:var(--blue); width:56px; }}
  .price-table td.lead-col {{ font-weight:700; color:var(--navy); white-space:nowrap; }}
  .doc-footer {{ margin-top:16px; padding-top:10px; border-top:2px solid var(--navy);
    display:flex; justify-content:space-between; gap:12px; font-size:8px;
    color:var(--gray-400); flex-wrap:wrap; }}
  @media print {{ body {{ background:var(--white)!important; padding:0; }}
    .page {{ box-shadow:none; padding:4mm 0; width:100%; min-height:auto; }} }}
  @page {{ size:A4; margin:18mm 20mm 24mm; }}
</style>

<div class="page">
  <div class="doc-header">
    <div>
      <div class="kicker">Annex 2a to the Reseller Agreement &middot; confidential (clause 11)</div>
      <h1>Price list &mdash;<br>procurement costs per case</h1>
    </div>
    <img src="betterco-logo.png" alt="BetterCo" style="height:22px">
  </div>
  <div class="doc-date">Founders1 GmbH &mdash; STP Business Information GmbH &middot; version of {retrieved}</div>

  <p style="font-size:10.5px;line-height:1.7;margin:0 0 16px">This Annex forms part of the Reseller Agreement in the version attached at signature. It is amended <strong>only under clause&nbsp;8.6</strong> &mdash; not before twelve months have run, then on 60 days' notice; for a change in a register's own fees on 30 days' notice with evidence, and STP may terminate the affected jurisdiction within 14 days. It is confidential under clause&nbsp;11.</p>

  <div class="section">
    <h2><span class="sec-num">1</span> Cost per tier</h2>
    <p>These are the amounts Annex&nbsp;2.1 refers to as &bdquo;the procurement cost for that jurisdiction&ldquo;. They are the <strong>procurement cost per case</strong> for a jurisdiction in that tier. The list price column is shown for orientation only and is not the basis of any settlement.</p>
    <div class="tablewrap">
      <table class="price-table">
        <thead><tr><th>Tier</th><th class="price">Procurement cost</th><th class="price">List price</th><th class="price">Jurisdictions</th></tr></thead>
        <tbody>
{rows}
        </tbody>
      </table>
    </div>
  </div>

  <div class="section">
    <h2><span class="sec-num">2</span> Individually priced jurisdictions</h2>
    <div class="tablewrap">
      <table class="price-table">
        <thead><tr><th>Jurisdiction</th><th class="price">Procurement cost</th><th>Sourced via</th></tr></thead>
        <tbody>
{ind}
        </tbody>
      </table>
    </div>
    <p>Founders1 procures {own} through its <strong>own routes</strong>. The remaining jurisdictions in the table above are individually priced but not own-sourced; the distinction matters for Annex&nbsp;2.5 and is recorded here rather than in the Agreement.</p>
    <p><strong>United States:</strong> the register is per state and availability is determined per state. The amount above is the contracted case fee and does not warrant that every state resolves.</p>
  </div>

  <div class="section">
    <h2><span class="sec-num">3</span> Surcharges</h2>
    <p>A case that has to be worked manually carries <strong>{manual}&nbsp;&euro;</strong> in addition. Surcharges for additional documents (Annex&nbsp;2.3) are per jurisdiction and per document kind and are added to this list as they are agreed; an amount not stated here is not charged.</p>
  </div>

  <div class="doc-footer">
    <span>Annex 2a &middot; Founders1 GmbH &middot; HRB 234373 B</span>
    <span>Confidential &mdash; not for onward disclosure</span>
  </div>
</div>
""".format(rows=u"\n".join(rows), ind=u"\n".join(ind), own=own,
           manual=MANUAL_SURCHARGE, retrieved=retrieved)

    with io.open(PRICE_LIST, "w", encoding="utf-8") as fh:
        fh.write(html)
    return PRICE_LIST


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--price-list", action="store_true")
    args = ap.parse_args()

    data = load()
    js = data["jurisdictions"]
    c = counts(js)
    total = len(js)

    frag_tiers = tiers_fragment(js)
    frag_juris = jurisdictions_fragment(js)

    if args.price_list:
        print("price list ->", write_price_list(js, data))
        if not (args.write or args.check):
            return 0

    if not (args.write or args.check):
        print(frag_tiers)
        print()
        print(frag_juris)
        return 0

    with io.open(DOC, encoding="utf-8") as fh:
        html = fh.read()

    if args.check:
        problems = []
        m = re.search(r"(\d+)\s+jurisdictions are covered", html)
        if not m:
            problems.append("cannot find the jurisdiction count sentence in Annex 2.2")
        elif int(m.group(1)) != total:
            problems.append("Annex 2.2 says %s jurisdictions, price_bands.json has %d"
                            % (m.group(1), total))
        # the legend chip is class="chip stp inline" and is deliberately not counted
        chips = len(re.findall(r'class="chip(?: stp)?">', html))
        if chips != total:
            problems.append("Annex 2.2 renders %d chips, price_bands.json has %d"
                            % (chips, total))
        for tier in ("A", "B", "C", "D"):
            pat = r'<td class="klass">%s</td><td class="price">(\d+)</td>' % tier
            mm = re.search(pat, html)
            if not mm:
                problems.append("tier %s row not found or reformatted" % tier)
            elif int(mm.group(1)) != c[tier]:
                problems.append("tier %s says %s jurisdictions, data has %d"
                                % (tier, mm.group(1), c[tier]))
        # amounts must NOT appear in the contract (they live in the price list)
        for tier, (cost, _) in TIER_COST.items():
            if cost + " &euro;" in html or cost + " €" in html:
                problems.append("procurement cost %s for tier %s appears in the "
                                "contract; amounts belong in the price list only"
                                % (cost, tier))
        if problems:
            print("DRIFT between price_bands.json and Annex 2:")
            for p in problems:
                print("  - " + p)
            return 1
        print("Annex 2 matches price_bands.json (%d jurisdictions, %s)"
              % (total, dict(c)))
        return 0

    html = splice(html, "2.1", frag_tiers)
    html = splice(html, "2.2", frag_juris, keep_lead=False)
    with io.open(DOC, "w", encoding="utf-8") as fh:
        fh.write(html)
    print("Annex 2 regenerated: %d jurisdictions, %s" % (total, dict(c)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
